# Generated by Django 4.2.2 on 2023-10-04 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uusername', models.CharField(max_length=200)),
                ('uparentsname', models.CharField(max_length=200)),
                ('uage', models.CharField(max_length=100)),
                ('uemail', models.EmailField(max_length=254)),
                ('uaddress', models.CharField(max_length=255)),
                ('upincode', models.CharField(max_length=10)),
                ('ucontactnumber', models.CharField(max_length=10)),
                ('udate', models.DateField()),
                ('unationality', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'student',
            },
        ),
    ]
